Vagrant::Config.run do |config|

  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  config.vm.share_folder("test-cases", "/share/test-cases", "./cases")
  config.vm.share_folder("contrib", "/share/contrib", "./contrib")
  config.vm.share_folder("reports", "/share/measures", "./reports")
  config.vm.share_folder("conf", "/share/conf", "./conf")

  config.vm.provisioner = :chef_solo

  config.chef.cookbooks_path = "conf/chef/cookbooks"
  config.chef.roles_path = "conf/chef/roles"

  config.chef.json.merge!({
    :popc => {
      :version => "popc_1.3.1beta_xdr",
    }
  })

  config.vm.define :master do |master_config|
    master_config.vm.network "33.33.33.10"
    master_config.chef.add_role "master"
  end

  config.vm.define :slave1 do |config|
    config.vm.network "33.33.33.11"
    config.chef.add_role "slave"
  end

end
